server:
  port: 8081
spring:
  dubbo:
  # 服务名称
    application: manage-web
    registry:
# zookeeper服务中心地址
      address: 192.168.243.130:2181
 # zookeeper通讯协议名称
      protocol: zookeeper
    protocol:
    # dubbo 通讯协议
      name: dubbo
# dubbo扫描包的路径
    base-package: com.atguigu.gmall

logging:
  level:
    root: debug

