server:
  port: 8086
spring:
  dubbo:
  # \u670D\u52A1\u540D\u79F0
    application: order-web
    registry:
# zookeeper\u670D\u52A1\u4E2D\u5FC3\u5730\u5740
      address: 192.168.243.130:2181
 # zookeeper\u901A\u8BAF\u534F\u8BAE\u540D\u79F0
      protocol: zookeeper
    protocol:
    # dubbo \u901A\u8BAF\u534F\u8BAE
      name: dubbo
# dubbo\u626B\u63CF\u5305\u7684\u8DEF\u5F84
    base-package: com.atguigu.gmall
    consumer:
      check: false
      timeout: 600000
  thymeleaf:
    cache: false
    mode: LBGACYHTML5
logging:
  level:
    root: info
