server:
  port: 8082
spring:
  dubbo:
  # 服务名称
    application: item-web
    registry:
# 服务地址
      address: 192.168.243.130:2181
 # zookeeper通讯协议名称
      protocol: zookeeper
    protocol:
    # dubbo通讯协议名称
      name: dubbo
# dubbo扫包路径
    base-package: com.atguigu.gmall
    consumer:
      timeout: 600000
      check: false
  thymeleaf:
    #缓存
    cache: false
    #验证
    mode: LEGACYHTML5
logging:
  level:
    root: info