server:
  port: 8080
spring:
  dubbo:
    application: user-web
    registry:
#      zookeeper注册中心的地址
      address: 192.168.243.130:2181
#     zookeeper的通讯协议的名称
      protocol: zookeeper
    protocol:
      name: dubbo
#    dubbo的服务的扫描路径
    base-package: com.atguigu.gmall

logging:
  level:
    root: debug
